services:
  db:
    image: 'mongo:7'
    container_name: qdb
    volumes:
      - ./dbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=discordbot
      - MONGO_INITDB_ROOT_PASSWORD=discordbot
      - MONGO_INITDB_DATABASE=discordbot
    command: mongod --quiet --logpath /dev/null 

  # mongo-express:
  #   image: mongo-express
  #   depends_on:
  #     - db    
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=discordbot
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=discordbot
  #     - ME_CONFIG_MONGODB_URL=mongodb://discordbot:discordbot@db:27017
  #     - ME_CONFIG_BASICAUTH=false

  app:
    image: 'dahool/qbot:latest'
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: qbot
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s    
    depends_on:
      - db
    env_file:    
      - ./bot/.env
    environment:
      - TZ=Etc/UTC
      - DASHBOARD_URL=http://localhost:3000
      - NODE_ENV=dev
      - DBCONN=mongodb://discordbot:discordbot@db:27017/discordbot?authSource=admin
    ports:
       - "3000:3000"